### ISSUE TITLE
SyntaxError: (unicode error)

### ISSUE THREAD

**Issue by jrwrigh** [pancho111203/vscode-ipython#1]
Hello, I'm getting an error when running the `ipython.sendFileContentsToIPython` command.

```python
In [2]: __file__ = 'c:\Users\U2berggeist\Documents\f1fantasy\main.py'
   ...: %load c:\Users\U2berggeist\Documents\f1fantasy\main.py
   ...:
  File "<ipython-input-2-49bbcba55e23>", line 1
    __file__ = 'c:\Users\U2berggeist\Documents\f1fantasy\main.py'
              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

Ran into this right out of the box, so I'm not sure what exactly the issue is. I'll look at it more as time permits.

**Comment by jrwrigh** [comment]
Looking through possible errors, I found [this](https://stackoverflow.com/a/1347854/7564988). 

Solution presented would be to add an `r` in front of the string to make it raw. This works when I enter in the following:

```python
In [7]: __file__ = r'c:\Users\U2berggeist\Documents\f1fantasy\main.py'
   ...: %load c:\Users\U2berggeist\Documents\f1fantasy\main.py
   ...:
```

**Comment by franciscorubin** [comment]
Fixed in the latest commit, thanks. I didn't see it before because I only tested in MacOS.

**Comment by jrwrigh** [comment]
Yeah, that's what I figured. That or Linux anyways.

**Comment by jrwrigh** [comment]
Has the new commit been put on the MarketPlace?

**Comment by franciscorubin** [comment]
@u2berggeist Yes, it's on version 0.4.0
